version: 2
project_name: terraform-provider-gns3

before:
  hooks:
    - go mod tidy
    - |
      bash -lc '
      set -euo pipefail
      VER="${GORELEASER_CURRENT_TAG:-}"; VER="${VER#v}"
      if [ -z "$VER" ]; then VER="${GITHUB_REF_NAME:-}"; VER="${VER#v}"; fi
      if [ -z "$VER" ]; then echo "ERROR: no version (tag) found"; exit 1; fi
      mkdir -p dist
      cat > "dist/terraform-provider-gns3_${VER}_manifest.json" << "EOF"
      {
        "version": 1,
        "metadata": {
          "protocol_versions": ["6.0"]
        }
      }
      EOF
      '
checksum:
  name_template: 'terraform-provider-gns3_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: 'dist/terraform-provider-gns3_{{ .Version }}_manifest.json'
      name_template: 'terraform-provider-gns3_{{ .Version }}_manifest.json'

signs:
  - id: gpg-sum
    artifacts: checksum
    cmd: gpg
    signature: "${artifact}.sig"
    args:
      - --batch
      - --yes
      - --pinentry-mode
      - loopback
      - --passphrase
      - "{{ .Env.PASSPHRASE }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"

release:
  draft: false
  prerelease: "false"
  extra_files:
    - glob: 'dist/terraform-provider-gns3_{{ .Version }}_manifest.json'
      name_template: 'terraform-provider-gns3_{{ .Version }}_manifest.json'
