version: 2
project_name: terraform-provider-gns3

before:
  hooks:
    - |
      bash -lc '
      set -euo pipefail
      VER="${GORELEASER_CURRENT_TAG:-}"
      VER="${VER#v}"
      if [ -z "$VER" ]; then
        VER="${GITHUB_REF_NAME:-}"
        VER="${VER#v}"
      fi
      if [ -z "$VER" ]; then
        echo "ERROR: could not detect version (GORELEASER_CURRENT_TAG/GITHUB_REF_NAME empty)"; exit 1
      fi
      cat > "terraform-provider-gns3_${VER}_manifest.json" << "EOF"
      {
        "version": 1,
        "metadata": {
          "protocol_versions": ["6.0"]
        }
      }
      EOF
      '

builds:
  - id: provider
    main: .
    env:
      - CGO_ENABLED=0          # static Linux binary
    ldflags:
      - -s -w
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    binary: 'terraform-provider-gns3_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    ignore:
      - goos: linux
        goarch: arm64          # only linux/amd64 + both darwin arches

archives:
  - id: zips
    formats: [zip]
    files: []
    name_template: 'terraform-provider-gns3_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'terraform-provider-gns3_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - id: gpg-sum
    artifacts: checksum
    cmd: gpg
    signature: "${artifact}.sig"
    args:
      - --batch
      - --yes
      - --pinentry-mode
      - loopback
      - --passphrase
      - "{{ .Env.PASSPHRASE }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"

release:
  draft: false
  prerelease: "false"          # must be a string in v2
  extra_files:
    - glob: "terraform-provider-gns3_*_manifest.json"
