project_name: terraform-provider-gns3

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archive:
  format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

sign:
  artifacts: checksum
  args:
    - '--batch'
    - '--yes'
    - '--armor'
    - '--detach-sign'
    - '--local-user'
    - '6DC4F58CC877B130'

release:
  github:
    owner: netopschic@gmail.com
    name: NetOpsChic/terraform-provider-gns3
