name: 'Terraform Provider Release'

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:  # This enables manual triggering

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Set up Go'
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: 'Import GPG Key'
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$PASSPHRASE" | gpg --batch --passphrase-fd 0 --edit-key 6DC4F58CC877B130 trust quit

      - name: 'Set up Goreleaser'
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest

      - name: 'Release'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: goreleaser release --rm-dist
